apps/login/urls.py
from django.conf.urls import url
from views import *
# from django.contrib import admin

urlpatterns = [
    url(r'^$', index, name = 'index'),
    url(r'^register$', register, name = 'registration'),
    url(r'^success$', success, name = 'success'),
    url(r'^login$', login, name = 'login'),
    url(r'^logout$', logout, name = 'logout')
    # url(r'^admin/', admin.site.urls),
]

apps/quotes/urls.py
from django.conf.urls import url
from views import *

urlpatterns = [
    url(r'^home$', home, name = "home"),
    url(r'^add_to_list/(?P<id>\d+)$', add_to_list, name = "add_to_list"),
    url(r'^add_quote$', add_quote, name= "add_quote"),
    url(r'^remove/(?P<id>\d+)$', remove, name="remove"),
    url(r'^user/(?P<id>\d+)$', user, name = "user"),
]

beltexam/urls.py
from django.conf.urls import url, include
# from django.contrib import admin

urlpatterns = [
    url(r'^', include('apps.login.urls', namespace='users')),
    url(r'^quotes/', include('apps.quotes.urls', namespace='quotes')),
    # url(r'^admin/', admin.site.urls),
]

apps/login/models.py
from __future__ import unicode_literals
from django.contrib import messages
from django.db import models
import bcrypt
import re


EMAIL_REGEX = re.compile (r'^[a-zA-Z0-9.+_-]+@[a-zA-Z0-9._-]+\.[a-zA-Z]+$')
# Create your models here.

class UserManager(models.Manager):
    def valid_registration(self, user_info, request):
        valid = True
        if not user_info['first_name'].isalpha():
            messages.warning(request, "First name must be all letters!")
            valid = False
        if len(user_info['first_name']) < 2:
            messages.warning(request, "First name must be 2 or more characters long!")
            valid = False
        if not user_info['last_name'].isalpha():
            messages.warning(request, "Last name must be all letters!")
            valid = False
        if len(user_info['last_name']) < 2:
            messages.warning(request, "Last name must be 2 or more characters long!")
            valid = False
        if not user_info['alias'].isalpha():
            messages.warning(request, "Alias must be all letters!")
            valid = False
        if len(user_info['alias']) < 2:
            messages.warning(request, "Alias must be 2 or more characters long!")
            valid = False
        if len(user_info['birthday']) < 6:
            messages.warning(request, "birthday must be 6 characters long!")
            valid = False
        if not EMAIL_REGEX.match(user_info['email_address']):
            messages.warning(request, "Email is not a valid email!")
            valid = False
        if len(user_info['password']) < 7:
            messages.warning(request, "Password is too short!")
            valid = False
        if user_info['password'] != user_info['confirm_password']:
            messages.warning(request, "Passwords do not match!")
            valid = False
        if User.objects.filter(email = user_info['email_address']):
            messages.error(request, "This Email already exists!")
            valid = False
        if valid == True:
            # messages.success(request, "Successful registration, " + user_info['first_name'] + "!")
            hashed = bcrypt.hashpw(user_info['password'].encode(), bcrypt.gensalt())
            User.objects.create(first_name = request.POST['first_name'], last_name = request.POST['last_name'], alias = request.POST['alias'], birthday = request.POST['birthday'], email = request.POST['email_address'], password = hashed)
        return valid

    def exisiting_user(self, user_info, request):
        valid = True
        if User.objects.filter(email = user_info['email_address']):
            hashed = User.objects.get(email = user_info['email_address']).password
            hashed = hashed.encode('utf-8')
            password = user_info['password']
            password = password.encode('utf-8')
            if bcrypt.hashpw(password, hashed) == hashed:
                # messages.success(request, "Success! Welcome back, " + User.objects.get(email = user_info['email_address']).first_name + "!")
                valid = True
            else:
                messages.warning(request, "Incorrect password!")
                valid = False
        else:
            messages.warning(request, "Your email is not correct!")
            valid = False
        return valid

class User(models.Model):
    first_name = models.CharField(max_length=45)
    last_name = models.CharField(max_length=45)
    email = models.EmailField()
    alias = models.CharField(max_length=45)
    password = models.CharField(max_length=45)
    birthday = models.CharField(max_length=10)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    UserManager = UserManager()
    objects = models.Manager()

apps/quotes/models.py
from __future__ import unicode_literals
from ..login.models import *
from django.db import models

# Create your models here.
class Quote(models.Model):
    posted_by = models.ForeignKey(User, related_name= "user_posts")
    author = models.CharField(max_length=45)
    message = models.TextField(max_length=500)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

class Favorite(models.Model):
    user = models.ForeignKey(User, related_name= "user_favorites")
    quote = models.ForeignKey(Quote, related_name = "quote_favorites")
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at= models.DateTimeField(auto_now=True)

apps/login/views.py
from django.shortcuts import render, redirect
from .models import *
from django.contrib import messages
from django.core.urlresolvers import reverse
# Create your views here.
def index(request):
    if 'first_name' not in request.session:
        return render(request, 'login/index.html')
    else:
        return redirect(reverse('quotes:home'))

def register(request):
    if User.UserManager.valid_registration(request.POST, request):
        valid = True
        user = User.objects.get(email = request.POST['email_address'])
        request.session['first_name'] = user.first_name
        request.session['user_id'] = user.id
        request.session['alias'] = user.alias
        return redirect(reverse('quotes:home'))
    else:
        valid = False
        return redirect(reverse('users:index'))

def success(request):
    return render(request, 'quotes/home.html')

def login(request):
    if User.UserManager.exisiting_user(request.POST, request):
        valid = True
        user = User.objects.get(email = request.POST['email_address'])
        request.session['first_name'] = user.first_name
        request.session['email_address'] = user.last_name
        request.session['user_id'] = user.id
        request.session['alias'] = user.alias
        return redirect(reverse('quotes:home'))
    else:
        valid = False
        return redirect(reverse('users:index'))

def logout(request):
    request.session.clear()
    return redirect(reverse('users:index'))

apps/quotes/views.py
from django.shortcuts import render, redirect
from .models import *
from django.core.urlresolvers import reverse
from django.contrib import messages

# Create your views here.
def home(request):
    quotes = Quote.objects.exclude(quote_favorites__user__id=request.session['user_id'])
    favorites = Favorite.objects.filter(user_id=request.session['user_id'])
    context={
        'quotes':quotes,
        'favorites': favorites
    }
    return render(request, 'quotes/home.html', context)

def add_to_list(request, id):
    Favorite.objects.create(quote_id=id, user_id=request.session['user_id'])
    return redirect(reverse('quotes:home'))

def add_quote(request):
    if len(request.POST['author']) < 3:
        messages.warning(request, "**Quoted By field must be at least 3 characters.**")
        return redirect(reverse('quotes:home'))
    if len(request.POST['message']) < 10:
        messages.warning(request, "**Message must be 10 characters or more.**")
        return redirect(reverse('quotes:home'))
    Quote.objects.create(author = request.POST['author'], message = request.POST['message'], posted_by_id=request.session['user_id'])
    return redirect(reverse('quotes:home'))

def remove(request, id):
    user=User.objects.get(id=request.session['user_id'])
    user.user_favorites.filter(quote_id=id).delete()
    return redirect(reverse('quotes:home'))

def user(request, id):
    user = User.objects.get(id=id)
    quotes = user.user_posts.all()
    total = len(quotes)
    context={
        'user':user,
        'quotes': quotes,
        'total':total
    }

    return render(request, 'quotes/user_quotes.html', context)

apps/login/templates/login/index.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
  <head>
    <meta charset="utf-8">
    <title>Login and Registration | Home </title>
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
    <link rel="stylesheet" href="{% static 'css/login.css' %}">
  </head>
  <body>
    <div class="container">
      {% if messages %}
        {% for message in messages %}
          {{message}}
        {% endfor %}
      {% endif %}
      <div class="jumbotron">
        <h1>Welcome to Quotes!</h1>
      </div>
      <h2>Login</h2>
      <form class="form-horizontal" action="{% url 'users:login' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
          <label class="control-label col-sm-2" for="email_address">Email Address</label>
          <div class="col-sm-6">
            <input type="email" class="form-control" name="email_address">
          </div>
        </div>
        <div class="form-group">
          <label class="control-label col-sm-2" for="password">Password</label>
          <div class="col-sm-6">
            <input type="password" class="form-control" name="password">
          </div>
        </div>
        <div class="form-group">
          <div class="col-sm-offset-2 col-sm-10">
            <button type="submit" class="btn btn-default">Login</button>
          </div>
        </div>
      </form>
      <h2>Registration</h2>
      <form class="form-horizontal" action="{% url 'users:registration' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
          <label class="control-label col-sm-2" for="email_address">Email Address</label>
          <div class="col-sm-6">
            <input type="email" class="form-control" name="email_address">
          </div>
        </div>
        <div class="form-group">
          <label class="control-label col-sm-2" for="first_name">First Name</label>
          <div class="col-sm-6">
            <input type="text" class="form-control" name="first_name">
          </div>
        </div>
        <div class="form-group">
          <label class="control-label col-sm-2" for="last_name">Last Name</label>
          <div class="col-sm-6">
            <input type="text" class="form-control" name="last_name">
          </div>
        </div>
        <div class="form-group">
          <label class="control-label col-sm-2" for="alias">Alias</label>
          <div class="col-sm-6">
            <input type="text" class="form-control" name="alias">
          </div>
        </div>
        <div class="form-group">
          <label class="control-label col-sm-2" for="birthday">Birthday</label>
          <div class="col-sm-6">
            <input type="date" class="form-control" name="birthday">
          </div>
        </div>
        <div class="form-group">
          <label class="control-label col-sm-2" for="password">Password</label>
          <div class="col-sm-6">
            <input type="password" class="form-control" name="password">
          </div>
        </div>
        <div class="form-group">
          <label class="control-label col-sm-2" for="confirm_password">Confirm Password</label>
          <div class="col-sm-6">
            <input type="password" class="form-control" name="confirm_password">
          </div>
        </div>
        <div class="form-group">
          <div class="col-sm-offset-2 col-sm-10">
            <button type="submit" class="btn btn-default">Register</button>
          </div>
        </div>
      </form>
    </div>
  </body>
</html>

apps/quotes/templates/quotes/home.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
  <head>
    <meta charset="utf-8">
    <title>Quotes</title>
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
    <link rel="stylesheet" href="{% static 'css/quotes.css' %}">
  </head>
  <body>
    <div class="container">
      <nav class="navbar navbar-default">
        <div class="container-fluid">
          <!-- Brand and toggle get grouped for better mobile display -->
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'quotes:home' %}">Quotes</a>
          </div>
          <!-- Collect the nav links, forms, and other content for toggling -->
          <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
              <li><a href="{% url 'quotes:home' %}">Home</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
              <li><a href="{% url 'users:logout' %}">Logout</a></li>
            </ul>
          </div><!-- /.navbar-collapse -->
        </div><!-- /.container-fluid -->
      </nav>
      {% if messages %}
        {% for message in messages %}
          {{message}}
        {% endfor %}
      {% endif %}
      <div class="page-header">
        <h1>Welcome, {{request.session.alias}}!</h1>
      </div>
        {% if quotes.exists %}
          <h3>Quotable Quotes</h3>
          {% for quote in quotes %}
          <div class="quotes">
            <h4>"{{quote.message}}"-{{quote.author}}</h4>
            <em><h5>Posted by: <a href="{% url 'quotes:user' id=quote.posted_by.id %}">{{quote.posted_by.alias}}</a></h5></em>
            <a href="{% url 'quotes:add_to_list' id=quote.id %}" class="btn btn-info" role="button">Add To List</a>
          </div>
          {% endfor %}
        {% else %}
          <h3>All quotes are added to favorites!</h3>
        {% endif %}

        <h3>Your Favorite Quotes</h3>
        {% for favorite in favorites %}
          {% if request.session.user_id == favorite.user.id %}
          <div class="quotes">
            <h4>"{{favorite.quote.message}}"-{{favorite.quote.author}}</h4>
            <em><h5>Posted By: <a href="{% url 'quotes:user' id=favorite.quote.posted_by.id %}">{{favorite.quote.posted_by.alias}}</a></h5></em>
            <a href="{% url 'quotes:remove' id=favorite.quote.id %}" class="btn btn-danger" role="button">Remove From List</a>
          </div>
          {% endif %}
        {% endfor %}

      <h3>Contribute a Quote</h3>
      <div class="add_quote">
        <form class="form-horizontal" action="{% url 'quotes:add_quote' %}" method="post">
          {% csrf_token %}
          <div class="form-group">
            <label class="control-label col-sm-1" for="quoted_by">Quoted By</label>
            <div class="col-sm-6">
              <input type="text" class="form-control" name="author">
            </div>
          </div>
          <div class="form-group">
            <label class="control-label col-sm-1" for="message">Message</label>
            <div class="col-sm-6">
              <textarea class="form-control" rows="5" name="message"></textarea>
            </div>
          </div>
          <div class="form-group">
            <div class="col-sm-offset-1 col-sm-10">
              <button type="submit" class="btn btn-default">Submit Quote</button>
            </div>
          </div>
        </form>
      </div>
    </div>
  </body>
</html>

apps/quotes/templates/quotes/user_quotes.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
  <head>
    <meta charset="utf-8">
    <title>User Quotes</title>
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
    <link rel="stylesheet" href="{% static 'css/quotes.css' %}">
  </head>
  <body>
    <div class="container">
      <nav class="navbar navbar-default">
        <div class="container-fluid">
          <!-- Brand and toggle get grouped for better mobile display -->
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'quotes:home' %}">Quotes</a>
          </div>
          <!-- Collect the nav links, forms, and other content for toggling -->
          <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
              <li><a href="{% url 'quotes:home' %}">Home</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
              <li><a href="{% url 'users:logout' %}">Logout</a></li>
            </ul>
          </div><!-- /.navbar-collapse -->
        </div><!-- /.container-fluid -->
      </nav>
      <div class="jumbotron">
        <h1>Posts by {{user.alias}}</h1>
        <p>Count: {{total}}</p>
      </div>
      {% for quote in quotes %}
      <div class="quotes">
        <h4>"{{quote.message}}" -{{quote.author}}</h4>
      </div>
      {% endfor %}
    </div>
  </body>
</html>